repos:
  # Basic built in into pre-commit linters (validate json, xml, yaml and toml syntax, ensure no merge conflicts and no trailing whitespaces)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        stages: [commit]
      - id: check-json
        stages: [commit]
      - id: check-xml
        stages: [commit]
      - id: check-yaml
        stages: [commit]
        args: [--unsafe]
      - id: check-toml
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: debug-statements
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: name-tests-test
        stages: [commit]
        args: ['--django']
      - id: no-commit-to-branch
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
      - id: pretty-format-json
        stages: [commit]
        args: [--autofix, --indent=4]
      - id: requirements-txt-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
        args: [--markdown-linebreak-ext=md]

  # Autoformats python code to a single standard
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        stages: [commit]
        args: ["--line-length=99"]

  # Groups and sorts python imports, see .isort.cfg for configuration
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        stages: [commit]

  # Markdown linter, see markdownlint.yaml for configuration
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint
        stages: [commit]
        args: ["--fix"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: /opt/conda/bin/pytest
        language: script
        pass_filenames: false
        always_run: true

  # Push hooks (runs on push because developers may commit incomplete changes)
  # Python files linter, see .pylintrc for configuration
  - repo: https://github.com/PyCQA/pylint
    rev: v2.10.2
    hooks:
      - id: pylint
        stages: [push]

  # Python security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        stages: [push]

fail_fast: true