name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and publish Streamlined to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install build dependencies
      run: >-
        python -m pip install setuptools build wheel
    - name: Build a binary wheel
      run: >-
        python setup.py bdist_wheel
        python setup.py sdist
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: CHANGELOG.txt
        files: |
          dist/streamlined-*.tar.gz
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
