name: Publish

on:
  push:
    tags:
      - v.*

jobs:
  build-and-publish:
    name: Build and publish Streamlined to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      if: ${{ github.ref == 'refs/heads/master' }}
    - name: Set up Python 3.9
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install build dependencies
      if: ${{ github.ref == 'refs/heads/master' }}
      run: >-
        python -m pip install setuptools build wheel
    - name: Build a binary wheel
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        python setup.py bdist_wheel
        python setup.py sdist
    - name: Release
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: softprops/action-gh-release@v1
      with:
        body_path: CHANGELOG.txt
        files: |
          dist/streamlined-*.tar.gz
    - name: Publish package
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
